name: Scrape sites at 1 AM
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Scrape sites 
        run: |
          curl --request GET \
          --url 'https://example.com/api/task' 